name: 'Setup Android Build Environment'
description: 'Setup Android build environment with Gradle caching'
inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '20'
  ruby-version:
    description: 'Ruby version'
    required: false
    default: '3.0'

runs:
  using: 'composite'
  steps:
    - name: 🛒 Setup Node and Yarn
      uses: ./.github/actions/setup-node-yarn
      with:
        node-version: ${{ inputs.node-version }}
        cache-key-suffix: 'android'
        
    - name: 💎 Setup Ruby
      uses: ./.github/actions/setup-ruby
      with:
        ruby-version: ${{ inputs.ruby-version }}
        working-directory: './android'
        
    - name: ☕ Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: 💾 Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          android/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: 🤖 Install Android Dependencies
      shell: bash
      run: yarn init-android
