jest.mock('react-native-nitro-player', () => ({
	TrackPlayer: {
		configure: jest.fn(),
		play: jest.fn(),
		pause: jest.fn(),
		seek: jest.fn(),
		getState: jest.fn().mockResolvedValue({}),
		skipToIndex: jest.fn(),
		skipToNext: jest.fn(),
		skipToPrevious: jest.fn(),
		onChangeTrack: jest.fn(),
		onPlaybackProgressChange: jest.fn(),
		onPlaybackStateChange: jest.fn(),
		onTracksNeedUpdate: jest.fn(),
		onSeek: jest.fn(),
		setRepeatMode: jest.fn(),
		getTracksNeedingUrls: jest.fn().mockResolvedValue([]),
		getActualQueue: jest.fn().mockResolvedValue([]),
		updateTracks: jest.fn(),
	},
	PlayerQueue: {
		getCurrentPlaylistId: jest.fn(),
		loadPlaylist: jest.fn().mockResolvedValue(undefined),
		getPlaylist: jest.fn(),
		createPlaylist: jest.fn(),
		addTrackToPlaylist: jest.fn(),
		addTracksToPlaylist: jest.fn(),
		removeTrackFromPlaylist: jest.fn(),
		reorderTrackInPlaylist: jest.fn(),
	},
	Equalizer: {
		setEnabled: jest.fn().mockResolvedValue(undefined),
		isEnabled: jest.fn().mockReturnValue(false),
		getBands: jest.fn().mockResolvedValue([]),
		setBandGain: jest.fn().mockResolvedValue(undefined),
		setAllBandGains: jest.fn().mockResolvedValue(undefined),
		getBandRange: jest.fn().mockReturnValue({ min: -12, max: 12 }),
		getPresets: jest.fn().mockReturnValue([]),
		getBuiltInPresets: jest.fn().mockReturnValue([]),
		getCustomPresets: jest.fn().mockReturnValue([]),
		applyPreset: jest.fn().mockResolvedValue(undefined),
		getCurrentPresetName: jest.fn().mockReturnValue(null),
		saveCustomPreset: jest.fn().mockResolvedValue(undefined),
		deleteCustomPreset: jest.fn().mockResolvedValue(undefined),
		getState: jest.fn().mockResolvedValue({ enabled: false, bands: [], currentPreset: null }),
		reset: jest.fn().mockResolvedValue(undefined),
		onEnabledChange: jest.fn(),
		onBandChange: jest.fn(),
		onPresetChange: jest.fn(),
	},
	DownloadManager: {
		configure: jest.fn(),
		downloadTrack: jest.fn(),
		deleteTrack: jest.fn(),
		deleteDownloadedTrack: jest.fn(),
		deleteAllDownloads: jest.fn(),
		getDownloadedTrack: jest.fn().mockResolvedValue(null),
		getDownloadedTracks: jest.fn().mockResolvedValue([]),
		getAllDownloadedTracks: jest.fn().mockResolvedValue([]),
		isTrackDownloaded: jest.fn().mockReturnValue(false),
		onDownloadComplete: jest.fn(),
	},
	RepeatMode: {
		None: 'none',
		One: 'one',
		All: 'all',
	},
	TrackPlayerState: {
		Playing: 'playing',
		Paused: 'paused',
		Stopped: 'stopped',
		Buffering: 'buffering',
		None: 'none',
	},
	useNowPlaying: jest.fn().mockReturnValue({ nowPlaying: undefined }),
	useOnPlaybackProgressChange: jest.fn().mockReturnValue({ position: 0, totalDuration: 0 }),
	useOnPlaybackStateChange: jest.fn().mockReturnValue({ state: 'none' }),
	useDownloadProgress: jest.fn().mockReturnValue({ progress: 0 }),
	useDownloadedTracks: jest.fn().mockReturnValue({ downloadedTracks: [] }),
	useEqualizer: jest.fn().mockReturnValue({
		isEnabled: false,
		bands: [31, 63, 125, 250, 500, 1000, 2000, 4000, 8000, 16000].map(
			(centerFrequency, index) => ({
				index,
				centerFrequency,
				gainDb: 0,
				frequencyLabel:
					centerFrequency >= 1000
						? `${centerFrequency / 1000} kHz`
						: `${centerFrequency} Hz`,
			}),
		),
		currentPreset: null,
		setEnabled: jest.fn().mockResolvedValue(true),
		setBandGain: jest.fn().mockResolvedValue(true),
		setAllBandGains: jest.fn().mockResolvedValue(true),
		reset: jest.fn().mockResolvedValue(undefined),
		isLoading: false,
		gainRange: { min: -12, max: 12 },
	}),
	useEqualizerPresets: jest.fn().mockReturnValue({
		presets: [],
		builtInPresets: [],
		customPresets: [],
		applyPreset: jest.fn().mockResolvedValue(true),
		saveCustomPreset: jest.fn().mockResolvedValue(true),
		deleteCustomPreset: jest.fn().mockResolvedValue(true),
		currentPreset: null,
		isLoading: false,
		refreshPresets: jest.fn(),
	}),
}))
