name: Publish Android APK and TestFlight Betas
on:
  push:
    branches:
      - 'main'
jobs:
  publish-ios-beta:
    runs-on: macos-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SIGNING_REPO_PAT }}

      - name: 🖥 Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 💬 Echo package.json version to Github ENV
        run: echo VERSION_NUMBER=$(npm version patch --tag-version-prefix="" --no-commit-hooks) >> $GITHUB_ENV

      - name: 🟢 Run npm run init
        run: npm run init

      - name: 🤫 Output App Store Connect API Key JSON to Fastlane
        run: echo -e '${{ secrets.APPSTORE_CONNECT_API_KEY_JSON }}' > appstore_connect_api_key.json
        working-directory: ./ios/fastlane

      - name: 🚀 Run iOS fastlane build and publish to TestFlight
        run: npm run fastlane:ios:beta
        env:
          APPSTORE_CONNECT_API_KEY_JSON: ${{ secrets.APPSTORE_CONNECT_API_KEY_JSON }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_REPO_PAT: "anultravioletaurora:${{ secrets.SIGNING_REPO_PAT }}"

      - name: 🚀 Run Android fastlane build
        run: npm run fastlane:android:build

      # Commit Fastlane Xcode build number increment
      - name: 🔢 Commit Xcode build number increment
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[skip actions]"
          file_pattern: "ios/Jellify.xcodeproj/project.pbxproj"

      - name: 🔢 Set artifact version numbers
        run: |
          # Move the iOS IPA
          mkdir artifacts
          mv ./ios/Jellify.ipa ./artifacts/Jellify-${{ env.VERSION_NUMBER }}.ipa

          # Move and rename all android release APKs
          for apk in ./android/app/build/outputs/apk/release/*.apk; do
            filename=$(basename "$apk")
            newname="Jellify-${{ env.VERSION_NUMBER }}-${filename}"
            cp "$apk" "./artifacts/$newname"
          done

      - name: 🎉 Create Github release 
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./artifacts/*"
          name: ${{ env.VERSION_NUMBER }}
          prerelease: true
          tag: ${{ env.VERSION_NUMBER }}
          token: ${{ secrets.SIGNING_REPO_PAT }}
